### PR TITLE
stop tweeting every commit

### PR DESCRIPTION
**Pull request by Spaak**
As described in #7 (ping @elshafeh), it would be desireable to stop tweeting every commit. This PR achieves this. (**Note**: I'm pretty sure this is all OK, but I have no way of testing the webhooks, so this is untested. Might be good to have a close look @robertoostenveld).

I'll file a different PR to solve https://github.com/fieldtrip/website/issues/8 (present list of commits on homepage) with a client-side widget.

(Note that I think it's indeed very important to stop tweeting every commit, since this is probably why many people do not follow @fieldtriptoolbx on twitter. A toolbox like ours should have 1,000s of followers, not a mere 812. The same argument, though to a lesser extent, can be made for not tweeting every "release", since our releases are not really releases but just daily updates. I'd say we should keep @fieldtriptoolbx for manually curated tweets, e.g. whenever major functionality is added, workshops are organized, or severe bugs are found.)

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I guess you missed that #7 was closed and the subsequent follow up. To reduce the clutter in dependencies and hard to maintain code, the nodejs webhook server has been abandoned in favour of https://github.com/fieldtrip/automation/commit/9dd1817ba8df2979145533fd289490da97910de4.

Before we discuss technical solutions, I would first want to see what the functional impact is. What is the content of the proposed tweets and when would they be sent out?

**Comment by Spaak** [comment]
> I guess you missed that #7 was closed and the subsequent follow up. To reduce the clutter in dependencies and hard to maintain code, the nodejs webhook server has been abandoned in favour of [9dd1817](https://github.com/fieldtrip/automation/commit/9dd1817ba8df2979145533fd289490da97910de4).

Ah, do I understand correctly that the file `webhook.js` in this repo was not used at all anymore? (So we should probably remove it.) In that case, what is the hook/script that is currently sending out the tweets upon commits? (I can't see anything doing so in 9dd1817).

> Before we discuss technical solutions, I would first want to see what the functional impact is. What is the content of the proposed tweets and when would they be sent out?

My idea with this PR was simply to disable the tweeting upon every commit. No new tweets are proposed here. (As I think it should be: we should probably not have any automated tweets, so that people actually want to be subscribed to our twitter account ;) )

Edit, to clarify: I think stopping tweeting every commit would be a significant improvement by itself, irrespective of whether or not we replace it with some other automated tweet (e.g. upon release, as suggested by #7).)

**Comment by robertoostenveld** [comment]
> Ah, do I understand correctly that the file webhook.js in this repo was not used at all anymore?

Yes, but I kept it for the time being since I was not sure that the new implementation would work reliably. Looking at https://twitter.com/fieldtriptoolbx it seems it does and it indeed can be deleted.

I currently have these two webhook handlers, both with a script in my homedir
```
roboos@mentat002> cat .webhook/website.sh 
#!/bin/bash
#
#PBS -l walltime=00:10:00
#PBS -l mem=100Mb
#
# This script is called as webhook from https://github.com/fieldtrip/website

if [ -r /etc/profile.d/optenv.sh ] ; then
source /etc/profile.d/optenv.sh
fi

echo building website... start
ssh roboos@fieldtrip website/_scripts/build.sh
echo building website... done
```

and 

```
roboos@mentat002> cat .webhook/fieldtrip.sh 
#!/bin/bash
#
#PBS -l walltime=00:05:00
#PBS -l mem=100Mb
#
# This script is called as webhook from https://github.com/fieldtrip/fieldtrip

if [ -r /etc/profile.d/optenv.sh ] ; then 
source /etc/profile.d/optenv.sh
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
rvm use 2.5.3

echo "webhook script start..."
/home/mrphys/roboos/fieldtrip/automation/send-tweet.sh
/home/mrphys/roboos/fieldtrip/automation/github.sh
/home/mrphys/roboos/fieldtrip/automation/release-nijmegen.sh
/home/mrphys/roboos/fieldtrip/automation/documentation.sh
echo "webhook script stop..."
```

The 2nd one takes care of all maintenance following a merge to the master branch fieldtrip/fieldtrip. The DCCN [webhook server ](https://github.com/Donders-Institute/hpc-webhook) schedules the script to run as a job on the cluster, i.e. it executes on a compute node. That is also why in the first I do  `ssh roboos@fieldtrip` (with a shared ssh key), because I want that to be executed on the webserver.

**Comment by robertoostenveld** [comment]
perhaps worthwhile to mention: both for building the website with Jekyll and for tweeting with [t](https://github.com/sferik/t) Ruby is needed. I am using `rvm` for that and have a Ruby installation with the required Gems under my personal account (i.e. ~roboos/.rvm/)

**Comment by robertoostenveld** [comment]
sorry, the link to 9dd1817 was not the right one, it is https://github.com/fieldtrip/automation/blob/master/send-tweet.sh

**Comment by Spaak** [comment]
Maybe we can have a brief Zoom chat about whether or not we *want* tweets
upon every commit?

**Comment by robertoostenveld** [comment]
let's discuss this in the next MEG meeting and have other users chime in. Or perhaps even ask on the mailing list?

**Comment by Spaak** [comment]
Sounds good! (I'd say discuss in MEG meeting first; maybe poll on the list later.)

**Comment by robertoostenveld** [comment]
Oh and it should not be about wanting option A yes or no, but about whether option A or option B is preferred. That is also why I think that option B needs to be clarified prior to asking people for input.

Right now people that do not want option A can simply unsubscribe from https://twitter.com/fieldtriptoolbx (or would not have subscribed in the first place). We do have 812 subscribers that appear to like option A (*). And we have been tweeting all commits since 2009 (with some periods with technical interruptions). 

*) even though unknowingly they might prefer B

**Comment by Spaak** [comment]
> That is also why I think that option B needs to be clarified prior to asking people for input.

I agree. I think we can use the MEG meeting to clarify the option(s) before we ask the list for input, though.

> We do have 812 subscribers that appear to like option A (*)

True, although I wonder how many of those have *not* muted the account while following it... This is purely subjective opinion, of course, but: I think it would be great to have a FieldTrip twitter account that can be used to communicate with users and the community when there is something of real value to be said (significant new functionality, severe bug, or workshops or so), without it being cluttered by commit/daily release messages.

~~(I say all this knowing that **I** was the one who came up with and implemented the tweet-on-commit thing years ago in the SVN days 🙈, but let's say "voortschrijdend inzicht" ;) )~~ This was only true for the wiki edits actually.

My proposed options so far (to be amended by MEG meeting):

(A) As-is; @fieldtriptoolbx keeps automatically tweeting all commits.
(B) @fieldtriptoolbx keeps auto-tweeting, but instead of every commit now auto-tweets every daily release.
(C.a) We stop all automated tweeting by @fieldtriptoolbx.
(C.b) Same as (C.a), except we make an additional new Twitter account ft_commits that takes over the role of tweeting all commits.
(C.c) Same as (C.a), except we make an additional new Twitter account ft_releases that auto-tweets the daily releases.
(C.d) We make 2 new Twitter accounts, combining C.b and C.c.

**Comment by schoffelen** [comment]
I would go for option (D): We reorganize the automation set-up such that automatic tweets are generated for each new news item that is posted on the website. These news items are either chunks of 'free text', announcements etc., with a tweetable header. In addition, each release (which these days is not daily) is then also announced as a news item (automatically), which is subsequently tweeted as somehing like "release year-date" is out" + a link that directs to a prettified git log, as per PR #7

**Comment by schoffelen** [comment]
This also pertains to https://github.com/fieldtrip/website/pull/271

**Comment by elshafeh** [comment]
I would also go for option D with some minor modifications. I agree with Eelke that tweeting every commit makes our account very liable to be muted or not followed. Now that I think of it more, I do not see much use to tweeting new releases, unless of course you're willing to add to it some daily wisdom or something. So I'm for stopping all automated tweets , announcing that we're stopping the automated tweets to get people back in the barn (couldn't think of a better metaphor) , and keep tweets to mirror more or less the "news section" + tweeting important updates to the code or new functionalities.

**Comment by schoffelen** [comment]
I am not on twitter myself, and I don't know at which point (i.e. frequency) tweets get annoying. Given the amount of followers of Donald Trump, I don't think that frequency per se (nor content) is a problem.

I think that tweeting only handcrafted news items leads to very infrequent activity, which I would also say could make people lose interest. The rationale for a new release (at most daily, but usually less frequent) is that a new release contains a couple of merged PRs, which typically are already squashed (i.e. not each commit is visible as a separate entity anymore), and intend to indeed resulted in an overall improvement of the code. It remains a matter of taste/subjectivitiy to consider some updates more important than others. For instance, people who don't do NIRS don't care about the recent important advances that were made w.r.t. support for NIRS data.

I would still be in favor of tweeting each release, with possibly the requirement for me and Robert (and other people who may be allowed to merge PRs in the future) to do a squash-merge as standard, and give a somewhat informative summary statement about each PR.

**Comment by robertoostenveld** [comment]
if there is wisdom to be shared, it needs to be typed in by someone, irrespective of where it ends up. Some people will like to see it on FaceBook, others on Instagram or on Twitter. However, the homepage and the mailing list are the only constant factors over the years; these are also not controlled by an external company. 

If there is some news or announcement, I think it makes sense to put it in the respective section on the homepage. And it makes sense to me to use other channels (like twitter) to amplify the effect of announcements.

perhaps it would be good to review the earlier considerations on 
- http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=793
- http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=816
- http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=994

**Comment by robertoostenveld** [comment]
this PR is obsolete since `webhook.js` is not being used anymore.

**Pull request closed without merging**
